# permissions for end users to view metallbscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: metallbscan-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: monitoring-wo-webhooks
    app.kubernetes.io/part-of: monitoring-wo-webhooks
    app.kubernetes.io/managed-by: kustomize
  name: metallbscan-viewer-role
rules:
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - metallbscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - metallbscans/status
  verbs:
  - get
