# permissions for end users to view portscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: portscan-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: container-scan
    app.kubernetes.io/part-of: container-scan
    app.kubernetes.io/managed-by: kustomize
  name: portscan-viewer-role
rules:
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - portscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - portscans/status
  verbs:
  - get
