# permissions for end users to edit vmscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vmscan-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: container-scan
    app.kubernetes.io/part-of: container-scan
    app.kubernetes.io/managed-by: kustomize
  name: vmscan-editor-role
rules:
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - vmscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - vmscans/status
  verbs:
  - get
