apiVersion: monitoring.spark.co.nz/v1alpha1
kind: VmScan
metadata:
  labels:
    app.kubernetes.io/name: container-scan
    app.kubernetes.io/managed-by: kustomize
  name: vmscan-sample
spec:
  # TODO(user): Add fields here
